In [3]:
import numpy as np

# 1 D array   
 creating a 1D array

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.arange(1,11,1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
even_spced_arr = np.linspace(0,100,5, dtype=int)
even_spced_arr

array([  0,  25,  50,  75, 100])

In [32]:
even_spced_array = np.linspace(0,100,5, dtype=int, endpoint=False)
even_spced_array

array([ 0, 20, 40, 60, 80])

In [36]:
char_arr = np.array(['Nikhilesh Mewara','Aayushi Mewara'])
char_arr

array(['Nikhilesh Mewara', 'Aayushi Mewara'], dtype='<U16')

# Accessing array

In [37]:
 c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], 
                 dtype = float)
 c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [38]:
c.ndim

3

# n-D array
creating  2 D arrays with 0 or 1     following methods can also create 1D array


In [26]:
all_zeros = np.zeros((4,4))
all_ones = np.ones((4,4))
all_empty = np.empty((4,4))
random = np.random.rand(4)

In [6]:
all_empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
all_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
all_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
random

array([0.30152849, 0.59237811, 0.25254584, 0.34356329])